// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Domain.Entities.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceOrders", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Technicians", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ServiceOrder", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("TEXT")
                                .HasColumnName("CustomerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("CustomerName");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("CustomerPhone");

                            b1.HasKey("ServiceOrderId");

                            b1.ToTable("ServiceOrders");

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Equipment", "Equipment", b1 =>
                        {
                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Brand")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("EquipmentBrand");

                            b1.Property<string>("Model")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("EquipmentModel");

                            b1.Property<string>("SerialNumber")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("EquipmentSerialNumber");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("EquipmentType");

                            b1.HasKey("ServiceOrderId");

                            b1.ToTable("ServiceOrders");

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Equipment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
